# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.CharField(max_length=128)),
                ('client_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('therapist_name', models.CharField(max_length=128)),
                ('therapist_surname', models.CharField(max_length=128)),
                ('contact_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('treatment_name', models.CharField(max_length=128)),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('therapist', models.ManyToManyField(to='bookings_app.Therapist')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings_app.Treatment'),
        ),
    ]
