# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='therapist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bookings_app.Therapist'),
            preserve_default=False,
        ),
    ]
